In [1]:
# Import data

In [2]:
import pandas as pd

In [5]:
pd.read_csv("data/20220915_HackZurich_Sensirion_v1.csv")

,Unnamed: 0,temperature_ventilation_system_fresh_air_in,temperature_ventilation_system_fresh_air_intermediate,temperature_ventilation_system_fresh_air_out,temperature_ventilation_system_used_air_in,temperature_ventilation_system_used_air_out,volumne_flow_ventitaltion_system_in,particulate_matter_outdoor_measured,temperature_outdoor,humidity_outdoor_measured,...,co2_room_A,co2_room_B,particulate_matter_room_A,tvoc_room_A,temperature_room_B,humidity_room_B,particulate_matter_room_B,no2_room_B,tvoc_room_B,consumed_meals
0,2021-05-02 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,0.382250,6.8924,42.4059,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1,2021-05-02 00:10:00,NaN,NaN,NaN,NaN,NaN,NaN,0.379375,6.9073,42.3694,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
2,2021-05-02 00:20:00,NaN,NaN,NaN,NaN,NaN,NaN,0.474375,6.8834,42.3726,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
3,2021-05-02 00:30:00,NaN,NaN,NaN,NaN,NaN,NaN,0.402085,6.8325,42.4241,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
4,2021-05-02 00:40:00,NaN,NaN,NaN,NaN,NaN,NaN,0.346685,6.8003,42.4528,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69980,2022-08-30 23:20:00,17.2,19.1,18.9,22.7,21.7,4.172,3.471660,18.0103,47.9157,...,NaN,486.814031,2.079261,110.791363,26.660517,49.210885,2.490608,1.000030,108.926326,0.0
69981,2022-08-30 23:30:00,17.1,19.0,18.8,22.7,21.7,4.230,3.422845,18.2474,47.9241,...,NaN,489.585671,2.204981,107.815045,26.621230,49.188966,2.513589,1.000030,110.349720,0.0
69982,2022-08-30 23:40:00,17.3,19.1,18.9,22.7,21.7,4.246,3.460525,18.2521,47.8984,...,NaN,492.433254,2.183570,110.722020,26.585029,49.239535,2.640214,1.000030,109.756101,0.0
69983,2022-08-30 23:50:00,17.5,19.3,19.1,22.7,21.8,4.207,3.590670,18.2713,47.8781,...,NaN,494.261124,2.179473,108.494947,26.542810,49.281673,2.457437,1.000039,111.564271,0.0
69984,2022-08-31 00:00:00,17.4,19.2,19.2,22.7,21.8,4.183,3.558755,18.2279,47.8944,...,NaN,490.632303,2.242919,111.492634,26.509236,49.402925,2.602873,1.013671,111.092115,0.0